In [1]:
import os
import sys
import pandas as pd

In [2]:
csv_filename = '../data/results.csv'
df = pd.read_csv(csv_filename)
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [6]:
def categorize_tournament(tournament_name):
    name = str(tournament_name).lower()

    if 'world cup' in name or 'copa américa' in name or 'euro' in name or 'nations cup' in name:
        if 'qualification' not in name and 'qualifying' not in name and 'qualifier' not in name:
            return 'Major Tournament'
    if 'qualification' in name or 'qualifying' in name or 'qor' in name or 'qualifier' in name:
        return 'Qualification'
    if 'friendly' in name:
        return 'Friendly'
    return 'Other / Regional Cup'
df = df[:-20]
df['tournament_type'] = df['tournament'].apply(categorize_tournament)

In [4]:
sys.path.append(os.path.abspath('..'))
from src.elo_system import calculate_elo_ratings

In [8]:
df = calculate_elo_ratings(df)
df.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,tournament_type,home_elo,away_elo
49460,2026-06-25,Ecuador,Germany,2.0,1.0,FIFA World Cup,East Rutherford,United States,True,Major Tournament,1932.251342,2007.891309
49461,2026-06-25,United States,Turkey,2.0,3.0,FIFA World Cup,Inglewood,United States,False,Major Tournament,1914.562107,1855.907135
49462,2026-06-25,Curaçao,Ivory Coast,0.0,2.0,FIFA World Cup,Philadelphia,United States,True,Major Tournament,1630.640958,1802.307624
49463,2026-06-25,Paraguay,Australia,0.0,0.0,FIFA World Cup,Santa Clara,United States,True,Major Tournament,1884.877335,1925.904409
49464,2026-06-25,Japan,Sweden,1.0,1.0,FIFA World Cup,Arlington,United States,True,Major Tournament,2006.019511,1762.580749

Just testing if elo system works.