In [1]:
import os
import sys
import pandas as pd

In [2]:
csv_filename = '../data/results.csv'
df = pd.read_csv(csv_filename)
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [3]:
def categorize_tournament(tournament_name):
    name = str(tournament_name).lower()

    if 'world cup' in name or 'copa américa' in name or 'euro' in name or 'nations cup' in name:
        if 'qualification' not in name and 'qualifying' not in name and 'qualifier' not in name:
            return 'Major Tournament'
    if 'qualification' in name or 'qualifying' in name or 'qor' in name or 'qualifier' in name:
        return 'Qualification'
    if 'friendly' in name:
        return 'Friendly'
    return 'Other / Regional Cup'
df = df[:-20]
df['tournament_type'] = df['tournament'].apply(categorize_tournament)

In [4]:
sys.path.append(os.path.abspath('..'))
from src.elo_system import calculate_elo_ratings
from src.features import add_form_features, add_h2h_feature

In [5]:
df.loc[49307, 'date'] = '2026-06-04'  # was testing the incorrect dated match's effect on features like elo
print(df.loc[49307]) 
df = calculate_elo_ratings(df)
df = add_form_features(df)
df = add_h2h_feature(df)
df.tail()

date                                                      2026-06-04
home_team                                                   Maldives
away_team                                                   Pakistan
home_score                                                       0.0
away_score                                                       3.0
tournament         Diamond Jubilee International Football Tournament
city                                                            Malé
country                                                     Maldives
neutral                                                        False
tournament_type                                 Other / Regional Cup
Name: 49307, dtype: object

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,tournament_type,home_elo,away_elo,home_average_goals_scored,home_average_conceded_goals,home_elo_momentum,away_average_goals_scored,away_average_conceded_goals,away_elo_momentum,h2h_win_pct
49480,2026-06-29,Netherlands,Morocco,1.0,1.0,FIFA World Cup,Guadalupe,Mexico,True,Major Tournament,2029.453504,2009.447459,2.4,1.2,19.911475,2.2,0.8,24.265652,0.666667
49481,2026-06-30,Ivory Coast,Norway,1.0,2.0,FIFA World Cup,Arlington,United States,True,Major Tournament,1826.720023,1947.689383,1.4,0.6,59.977175,2.4,1.8,51.560523,0.500000
49482,2026-06-30,France,Sweden,3.0,0.0,FIFA World Cup,East Rutherford,United States,True,Major Tournament,2162.092944,1780.721423,2.8,1.0,27.561125,2.0,2.4,48.005040,0.800000
49483,2026-06-30,Mexico,Ecuador,2.0,0.0,FIFA World Cup,Mexico City,Mexico,False,Major Tournament,1984.518385,1968.681424,2.4,0.2,36.701546,1.4,0.6,-65.251216,0.200000
49484,2026-07-01,England,DR Congo,2.0,1.0,FIFA World Cup,Atlanta,United States,True,Major Tournament,2100.234883,1806.100274,2.0,0.4,-1.669207,1.0,1.0,24.139232,0.500000

nice