In [1]:
import os
import sys
import pandas as pd
sys.path.append(os.path.abspath(".."))

from src.preprocessing import preprocess

In [2]:
csv_filename = '../data/results.csv'
df = pd.read_csv(csv_filename)
df.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49500,2026-07-07,Switzerland,Colombia,0.0,0.0,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,NaN,NaN,FIFA World Cup,Foxborough,United States,True
49502,2026-07-10,Spain,Belgium,NaN,NaN,FIFA World Cup,Inglewood,United States,True
49503,2026-07-11,Norway,England,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49504,2026-07-11,Argentina,Switzerland,NaN,NaN,FIFA World Cup,Kansas City,United States,True

In [3]:
df = preprocess(df)
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,tournament_type,...,h2h_win_pct,elo_diff,home_average_goals_scored,home_average_conceded_goals,home_elo_momentum,away_average_goals_scored,away_average_conceded_goals,away_elo_momentum,conceded_goals_diff,scored_goals_diff
34912,2011-07-07,Bolivia,Costa Rica,0.0,2.0,Copa América,San Salvador de Jujuy,Argentina,True,Major Tournament,...,0.00,-97.388220,0.4,1.6,3.747245,1.4,1.4,-7.054369,0.2,-1.0
34913,2011-07-07,Solomon Islands,Vanuatu,2.0,1.0,Friendly,Honiara,Solomon Islands,False,Friendly,...,0.75,83.709401,2.7,1.8,-42.791778,0.9,1.7,-34.665911,0.1,1.8
34914,2011-07-08,Aruba,Saint Lucia,4.0,2.0,FIFA World Cup qualification,Oranjestad,Aruba,False,Qualification,...,0.50,-195.192814,0.7,3.2,-74.315858,0.7,3.1,-78.342165,0.1,0.0
34915,2011-07-08,Dominican Republic,Anguilla,2.0,0.0,FIFA World Cup qualification,San Cristóbal,Dominican Republic,False,Qualification,...,0.75,245.946371,2.6,2.3,7.631400,0.8,3.9,-44.117822,-1.6,1.8
34916,2011-07-08,Jordan,Yemen,4.0,0.0,Friendly,Istanbul,Turkey,True,Friendly,...,0.50,201.007469,1.1,1.3,23.923712,1.5,2.0,9.046563,-0.7,-0.4